//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroptimalLabSW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CroptimalLabSW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absorption.
        /// </summary>
        public static string Absorption {
            get {
                return ResourceManager.GetString("Absorption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Configuration.
        /// </summary>
        public static string AddConfiguration {
            get {
                return ResourceManager.GetString("AddConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromameter.
        /// </summary>
        public static string Chromameter {
            get {
                return ResourceManager.GetString("Chromameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Page.
        /// </summary>
        public static string ClearPage {
            get {
                return ResourceManager.GetString("ClearPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Results.
        /// </summary>
        public static string ClearResults {
            get {
                return ResourceManager.GetString("ClearResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Configuration.
        /// </summary>
        public static string EditConfiguration {
            get {
                return ResourceManager.GetString("EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elechem.
        /// </summary>
        public static string Elechem {
            get {
                return ResourceManager.GetString("Elechem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Name.
        /// </summary>
        public static string ElementName {
            get {
                return ResourceManager.GetString("ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable warm up.
        /// </summary>
        public static string EnableWarmUp {
            get {
                return ResourceManager.GetString("EnableWarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists name.
        /// </summary>
        public static string ExistsName {
            get {
                return ResourceManager.GetString("ExistsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEDs Update.
        /// </summary>
        public static string LEDsUpdate {
            get {
                return ResourceManager.GetString("LEDsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIR.
        /// </summary>
        public static string NIR {
            get {
                return ResourceManager.GetString("NIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomic Order.
        /// </summary>
        public static string PolynomicOrder {
            get {
                return ResourceManager.GetString("PolynomicOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports Manage.
        /// </summary>
        public static string PortsManage {
            get {
                return ResourceManager.GetString("PortsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R².
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read BG.
        /// </summary>
        public static string ReadBG {
            get {
                return ResourceManager.GetString("ReadBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        public static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample ID.
        /// </summary>
        public static string SampleID {
            get {
                return ResourceManager.GetString("SampleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Edit.
        /// </summary>
        public static string SaveAndEdit {
            get {
                return ResourceManager.GetString("SaveAndEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Calibration.
        /// </summary>
        public static string SaveCalibration {
            get {
                return ResourceManager.GetString("SaveCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Results.
        /// </summary>
        public static string SaveResults {
            get {
                return ResourceManager.GetString("SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string SelectElement {
            get {
                return ResourceManager.GetString("SelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Element.
        /// </summary>
        public static string SetElement {
            get {
                return ResourceManager.GetString("SetElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Measurement.
        /// </summary>
        public static string SingleMeasure {
            get {
                return ResourceManager.GetString("SingleMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Up.
        /// </summary>
        public static string WarmUp {
            get {
                return ResourceManager.GetString("WarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Up Time [Sec].
        /// </summary>
        public static string WarmUpTime {
            get {
                return ResourceManager.GetString("WarmUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with Detector:.
        /// </summary>
        public static string WorkWithDetector {
            get {
                return ResourceManager.GetString("WorkWithDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xray.
        /// </summary>
        public static string Xray {
            get {
                return ResourceManager.GetString("Xray", resourceCulture);
            }
        }
    }
}
