//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CroptimalLabSW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CroptimalLabSW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromameter.
        /// </summary>
        public static string Chromameter {
            get {
                return ResourceManager.GetString("Chromameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elechem.
        /// </summary>
        public static string Elechem {
            get {
                return ResourceManager.GetString("Elechem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Name.
        /// </summary>
        public static string ElementName {
            get {
                return ResourceManager.GetString("ElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment.
        /// </summary>
        public static string Measurment {
            get {
                return ResourceManager.GetString("Measurment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIR.
        /// </summary>
        public static string NIR {
            get {
                return ResourceManager.GetString("NIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomic Order.
        /// </summary>
        public static string PolynomicOrder {
            get {
                return ResourceManager.GetString("PolynomicOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R².
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read BG.
        /// </summary>
        public static string ReadBG {
            get {
                return ResourceManager.GetString("ReadBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetitions.
        /// </summary>
        public static string Repetitions {
            get {
                return ResourceManager.GetString("Repetitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Calibration.
        /// </summary>
        public static string SaveCalibration {
            get {
                return ResourceManager.GetString("SaveCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string SelectElement {
            get {
                return ResourceManager.GetString("SelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xray.
        /// </summary>
        public static string Xray {
            get {
                return ResourceManager.GetString("Xray", resourceCulture);
            }
        }
    }
}
